project_id = "cthhyjobjxdyknzcieyq"

[functions.summarize-url]
verify_jwt = false

[functions.image-search]
verify_jwt = false

[functions.video-search]
verify_jwt = false

[functions.news-search]
verify_jwt = false

[functions.feedback-ai]
verify_jwt = false

[functions.generate-blueprint]
verify_jwt = false

[functions.poi-api]
verify_jwt = false

[functions.poi-live]
verify_jwt = false

[functions.poi-live-search]
verify_jwt = false

[functions.ayrshare-post]
verify_jwt = false
