import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Brain, Eye, Zap, Search, ExternalLink } from "lucide-react";
import { api as supabase } from "@/lib/api";
import SEOHead from "@/components/SEOHead";
import ShareButtons from "@/components/ShareButtons";

interface SharedSearch {
  id: string;
  query: string;
  answer: string;
  sources: any[];
  view_count: number;
  created_at: string;
}

const SharedSearch = () => {
  const { slug } = useParams<{ slug: string }>();
  const [data, setData] = useState<SharedSearch | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!slug) return;
    (async () => {
      const { data: row } = await supabase
        .from("shared_searches")
        .select("*")
        .eq("slug", slug)
        .single();
      if (row) {
        setData(row as SharedSearch);
        supabase.rpc("increment_shared_view" as any, { search_id: row.id });
      }
      setLoading(false);
    })();
  }, [slug]);

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!data) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center gap-4">
        <p className="text-muted-foreground">This shared insight was not found.</p>
        <Link to="/" className="text-primary hover:underline">Go to SEARCH-POI</Link>
      </div>
    );
  }

  const ogDescription = data.answer.slice(0, 155) + (data.answer.length > 155 ? "..." : "");

  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title={`${data.query} — SEARCH-POI Intelligence`}
        description={ogDescription}
        path={`/shared/${slug}`}
      />

      {/* Smart banner */}
      <div className="bg-primary/10 border-b border-primary/20 py-3 px-4">
        <div className="container mx-auto max-w-3xl flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <Zap className="w-5 h-5 text-primary" />
            <span className="font-bold text-foreground">SEARCH<span className="text-primary">-POI</span></span>
          </Link>
          <Link
            to={`/search?q=${encodeURIComponent(data.query)}`}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors"
          >
            <Search className="w-4 h-4" />
            Try your own search
          </Link>
        </div>
      </div>

      <main className="container mx-auto max-w-3xl px-4 py-10">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-medium mb-4">
            <Brain className="w-3 h-3" />
            Generated by SEARCH-POI Intelligence
          </div>

          <h1 className="text-2xl sm:text-3xl font-bold text-foreground mb-2">{data.query}</h1>

          <div className="flex items-center gap-4 text-xs text-muted-foreground mb-6">
            <span className="flex items-center gap-1"><Eye className="w-3 h-3" /> {data.view_count + 1} views</span>
            <span>{new Date(data.created_at).toLocaleDateString()}</span>
          </div>

          {/* AI Answer */}
          <div className="glass rounded-2xl p-6 mb-6">
            <div className="prose prose-sm max-w-none">
              <div className="text-secondary-foreground leading-relaxed whitespace-pre-wrap">{data.answer}</div>
            </div>
          </div>

          {/* Sources */}
          {Array.isArray(data.sources) && data.sources.length > 0 && (
            <div className="glass rounded-xl p-4 mb-6">
              <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">Verified Sources</h3>
              <div className="space-y-2">
                {data.sources.map((s: any, i: number) => (
                  <a key={i} href={s.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-sm text-primary hover:underline">
                    <ExternalLink className="w-3 h-3 shrink-0" />
                    {s.title || s.url}
                  </a>
                ))}
              </div>
            </div>
          )}

          <div className="flex items-center justify-between">
            <ShareButtons text={data.answer} query={data.query} />
          </div>

          {/* CTA */}
          <div className="mt-10 text-center glass rounded-2xl p-8">
            <Zap className="w-8 h-8 text-primary mx-auto mb-3" />
            <h2 className="text-xl font-bold text-foreground mb-2">Want AI-powered answers?</h2>
            <p className="text-muted-foreground text-sm mb-4">SEARCH-POI gives you instant AI intelligence for any question.</p>
            <Link
              to="/"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
            >
              <Search className="w-4 h-4" />
              Start Searching Free
            </Link>
          </div>
        </motion.div>
      </main>
    </div>
  );
};

export default SharedSearch;
